"""create a task table

Revision ID: db81792f7530
Revises: 
Create Date: 2026-06-30 09:01:07.474699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db81792f7530'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_no', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('task_no')
    )
    op.create_index(op.f('ix_tasks_task_no'), 'tasks', ['task_no'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_no'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
